export {default as Login} from './Login/Login';
export {default as Home} from './Home/Home';
export {default as Tutorial} from './Tutorial/Tutorial';
export {default as Login1} from './Login1/Login1';
export {default as SignUp} from './SignUp/SignUp';
export {default as verifyOtp} from './VerifyOtp/VerifyOtp';
export {default as SetPassword} from './SetPassword/SetPassword';
export {default as Profile} from './Profile/Profile';
export {default as Add} from './Add/Add';
export {default as Search} from './Search/Search'
export {default as Notification} from './Notification/Notification';
export {default as PostDetails} from './PostDetails/PostDetails';
export {default as EditProfile} from './EditProfile/EditProfile';