export default {
  LOGIN: 'login',
  LOGIN1: 'login1',
  HOME: 'home',
  TUTORIAL: 'tutorial',
  SIGNUP: 'signup',
  VERIFY_OTP: 'verifyOtp',
  SET_PASSWORD: 'set_password',
  PROFILE: 'profile',
  ADD: 'add',
  SEARCH: 'search',
  NOTIFICATION: 'notification',
  BOTTOM_TAB: 'bottomTab',
  POST_DETAILS: 'postDetails',
  EDIT_PROFILE: 'editProfile',
  ADD_INFO: 'AddInfo',
};
